version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /var/www/session/mysql/config:/etc/mysql/conf.d

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - 8080:8080

  golang:
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "8088:8088"
    volumes:
      - /var/www/session/mysql/logs:/var/logs