version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always

  golang:
    build: .
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - "8088:8088"
    volumes:
      - /var/www/session/redis/logs:/var/logs